### ISSUE TITLE
OG Content View Not Working

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/og#108]
First of all, like some of the other provided views, this one comes with only a Master display, which means that before it can be placed as a block, you must first edit the view and create a block display. 

I think it should come with a block display by default, since it is mostly likely to be used as a block. 

I believe that there is also a problem with the contextual filter, which is not working for me. Because, there is often more than one way to accomplish something in views AND because I'm not at expert at "Contextual Filters" I am not certain that it is not either user error or a misunderstanding about this is supposed to work. 

I will provide a PR with my version of the same view, which seems to work - and we can discuss if my approach is better or not.

STEPS TO REPRODUCE:

1) Enable all the OG modules on a fresh site.
2) Add/enable the demo content sub-module (if not yet merged)
3) Go to default layout and try to add "OG Content" view. You won't be able to, because it does not provide a block. 
4) Go to OG Content view (/admin/structure/views/view/og_nodes) and add a block
5) Go to default layout and add "OG Content" block
6) Go to a group page (example: /group/theme-developers) and note that there is no view of group content. 

Do the same thing with the view in my PR and you can skip steps 3 and 4 and in step 6 you will see a contextual view of the content for that group.

**Comment by stpaultim** [comment]
I pushed my PR with a different version of the view. I also changed the machine name to match the human name. The machine name is very close to the human name for all the views, except this one.

**Comment by argiepiano** [comment]
@stpaultim question: did you have og_context enabled?  As discussed in #80 (of which this seems to be a duplicate) you must enable og_context in order for the `Current OG group from context` to appear as one of the default values in the contextual filter when a value is not available.

This is the most efficient way to make this view work.

**Comment by olafgrabienski** [comment]
> As discussed in https://github.com/backdrop-contrib/og/issues/80 (of which this seems to be a duplicate) ...

Thanks for the hint @argiepiano! Hey @stpaultim, are you up to close this issue as a duplicate and chime in at #80? Over there is already some more information and discussion about the OG content view.

**Comment by stpaultim** [comment]
Sorry, didn't see that one. I'll test this again with the hint from @argiepiano and if necessary comment in the other issue.
