### ISSUE TITLE
Unable to add an og membership type

### ISSUE THREAD

**Issue by VasasA** [backdrop-contrib/og#11]
The page `admin/config/group/group-membership/add` shows an error message: `Fatal error: Declaration of OgMembershipType::__construct() must be compatible with EntityInterface::__construct(array $values) in <root>\modules\og\includes\og.membership_type.inc on line 7`

Maybe: Insert `array` before `$values` into <root>\modules\og\includes\og.membership_type.inc into line 12!

This results a new error message: `Fatal error: Class OgMembershipType contains 4 abstract methods and must therefore be declared abstract or implement the remaining methods (EntityInterface::id, EntityInterface::entityType, EntityInterface::label, ...) in <root>\modules\og\includes\og.membership_type.inc on line 7`

Related commit (this commit may contain some bad solutions :disappointed:  ): https://github.com/VasasA/og/commit/0cc46b03a88c222d7deb144c07b54459fbf58401

**Comment by laryn** [comment]
Fixed in the `issue-1` branch, which I'll merge into 1.x-2.x shortly.
