### ISSUE TITLE
D7 upgrade

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/og#117]
This issue compiles problems detected when upgrading an OG site from D7.

- [x] Despite the recent changes in Backdrop core 1.22.0, the stub module for entity_plus IS needed. This is a special case, given that OG extends `EntityPlusDefaultViewsController`  and this is in a `og.views.inc` which is loaded early on in the upgrade process by Views, before Entity Plus is automatically enabled.  This means that the README (which I recently modified) needs to include mention of this

**Comment by argiepiano** [comment]
I have added directions to the Wiki and revised the Readme file

**Comment by olafgrabienski** [comment]
@argiepiano Thanks! As some Wiki URLs changed in the meantime, the links from the README to single Wiki pages don't work. Maybe it's better to point to the Wiki main page, at least for the moment.

**Comment by argiepiano** [comment]
Good point. Thanks
