### ISSUE TITLE
Testing suggestions (wanted)

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/og#13]
Looking for hints on the best way to test - at the current stage of development. 

I've been enabling all the OG modules (except the feature). Is this bad? Would it be better, for now, to focus on the main module and UI module?

**Comment by laryn** [comment]
I think we're at a point where we can branch out to all the submodules, too. I haven't done that yet.

**Comment by VasasA** [comment]
@stpaultim  I think this is a simple and efficient way to test: Follow this video tutorial: http://modulesunraveled.com/organic-groups

**Comment by olafgrabienski** [comment]
@stpaultim FYI, see https://github.com/backdrop-contrib/og/issues/30#issuecomment-1057844774 and https://github.com/backdrop-contrib/og/issues/45.

**Comment by argiepiano** [comment]
Since @olafgrabienski provided a comprehensive guideline to testing in #45, I'm closing this as resolved.
