### ISSUE TITLE
In OG field settings, selecting a field without having selected an entity bundle throws notices

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/og#132]
In Configuration > Organic Groups > OG field settings, If you select a field (thereby triggering the AJAX callback) before having selected an entity bundle, Backdrop will throw PHP notices. The validate function must catch this.

<img width="866" alt="Screen Shot 2022-05-28 at 8 24 50 PM" src="https://user-images.githubusercontent.com/9938978/170849401-e4a7b827-b472-4929-854a-b366db27cf2b.png">

**Comment by laryn** [comment]
Likewise, I'm comfortable merging. LGTM!
