### ISSUE TITLE
Notice: Trying to access array offset on value of type bool in og_context_determine_context()

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/og#135]
After upgrading a site from D7 to Backdrop, I see the following notice on many pages of the Backdrop site:

> Trying to access array offset on value of type bool in og_context_determine_context() (line 450 of modules/og/og_context/og_context.module)

There is a [D7 issue](https://www.drupal.org/project/og/issues/3174097) which was fixed about two years ago. There hasn't been a new D7 Organic Groups release since then, so the fix was only [committed to the dev branch](https://git.drupalcode.org/project/og/-/commit/8092ab2ab51322839af81bce48d95ba257f33206).

**Comment by olafgrabienski** [comment]
Applying the D7 fix to Backdrop by changing https://github.com/backdrop-contrib/og/blob/1.x-2.x/og_context/og_context.module#L450 from

`if (strpos($item['path'], $path) === 0) {`

to

`if ($item && strpos($item['path'], $path) === 0) {`

fixes the issue for me.

**Comment by argiepiano** [comment]
Thanks, @olafgrabienski. This looks like the correct fix. Would you like to submit a PR? :)

**Comment by olafgrabienski** [comment]
Sure, PR submitted: https://github.com/backdrop-contrib/og/pull/136

**Comment by argiepiano** [comment]
Thank you much, @olafgrabienski! LGTM. @laryn, should I go ahead and merge?

**Comment by laryn** [comment]
LGTM too -- thanks @olafgrabienski!

**Comment by argiepiano** [comment]
Thanks! Merged!
