### ISSUE TITLE
Unable to create a node of type Group Type

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/og#14]
In following the installation instructions from the ReadMe file, I'm able to get to step 4. Creating a group of type = Group

I get the following PHP error.

Fatal error: Class OgMembership contains 4 abstract methods and must therefore be declared abstract or implement the remaining methods (EntityInterface::id, EntityInterface::entityType, EntityInterface::label, ...) in /app/backdrop/modules/og/includes/og.membership.inc on line 0

I am also seeing this in the logs, but it may not be related to this problem

Notice: Undefined index: og_behavior in EntityReference_BehaviorHandler_Abstract->__construct() (line 161 of /app/backdrop/modules/entityreference/plugins/behavior/abstract.inc).

**Comment by laryn** [comment]
Strange that I haven't gotten this. What version of PHP?

**Comment by stpaultim** [comment]
I'm using the default Lando recipe for Backdrop. The site status page says its on PHP Version: 7.2.34.

**Comment by laryn** [comment]
Which submodules are active when you get this?

**Comment by stpaultim** [comment]
This happened when following the instructions directly from README, which means ONLY enabling og and og_ui (and dependencies). 

I take it that you are unable to reproduce. Maybe I should try this again and make sure it's not user error on my part.

**Comment by VasasA** [comment]
@laryn Please see this [issue](https://github.com/laryn/og/issues/11), you will able to reproduce this error "Fatal error: Class OgMembership contains 4 abstract methods..."

**Comment by stpaultim** [comment]
Steps to recreate using Lando locally. 

1) Dropped database and started over with fresh database and install.
2) Install the following modules
	- Organic groups
	- Organic groups UI
	- Entity Plus
	- Entity UI
 	- Entity Reference
3) Create a new content type via admin/structure/types/add. Call it "Group", and define it to be of Group type.
4) Create a second content type. Call it "Group content", and set it to be of Group content type.
5) Add a Group by going to node/add/group. Call it First group, and enable the Group through the "Group type" field.

At this step, I am not seeing the option to enable the Group through a "Group Type" field and when I click save I get the following PHP error (white screen):

Fatal error: Class OgMembership contains 4 abstract methods and must therefore be declared abstract or implement the remaining methods (EntityInterface::id, EntityInterface::entityType, EntityInterface::label, ...) in /app/backdrop/modules/og/includes/og.membership.inc on line 0

**Comment by laryn** [comment]
My bad, I was reading on my phone and didn't understand the issue 😦

I guess this is because the `Entity` class is not an abstract class in Drupal's Entity API module, but it is in Backdrop. I'll do a little research...

**Comment by laryn** [comment]
@stpaultim @VasasA We may need to revisit in the future, but I've implemented mostly placeholder methods for the moment to get past this and continue testing.
