### ISSUE TITLE
Port or delete 'OG Features'

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/og#2]
The very first thing I did after downloading the module was went to install it. I immediately found the 'OG Features' module and correctly assumed that this based upon the Drupal Features module. 

Apparently that was a feature (Drupal Features module) that added configuration to demonstrate the OG capabilities.

I don't know if we are going to have a good way to do the same thing in BackdropCMS, other than writing a custom module that does the same thing. I would expect that this sub-module is not required. 

Does this just get removed or is there another strategy for this?

**Comment by laryn** [comment]
Agreed, I think we can delete that and reassess later how we could do similar.

**Comment by VasasA** [comment]
Related: https://github.com/backdrop-contrib/feeds/issues/20
> remove ... since Features likely won't be ported

**Comment by stpaultim** [comment]
Yeah, I don't expect to see a features solution here. However, one could replace the features module with a completely independent custom module that does the same thing (I think). But, that is probably not necessary?
