### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/og#21]
I chopped some text out of the README and put it in [the Wiki](https://github.com/backdrop-contrib/og/wiki) -- feel free to add/edit/revise content there.

**Comment by laryn** [comment]
I also opened up the Wiki for general editing (didn't realize it was restricted until recently).

**Comment by argiepiano** [comment]
I feel that we can close this now, since the Wiki is up and running, and people have contributed to the info there.
