### ISSUE TITLE
Add a CSS file for OG, and provide margin for two OG fields as a start

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/og#26]
Tested with Posts as group content: On a post with tags, the group name (`field-name-og-group-ref`) can't be distinguished from the tags. Example:

> Alpha
> Omega
> Group One

Proposal: add margin-top of `1rem` or so, result:

> Alpha
> Omega
> 
> Group One

**Comment by olafgrabienski** [comment]
When comments are open, things get even worse:

> Alpha
> Omega
> Group One
> Log in to post comments

So, let's add `margin: 1rem 0;` to `field-name-og-group-ref`, resulting approx. in:

> Alpha
> Omega
> 
> Group One
>
> Log in to post comments

Edit: not sure if there's already any frontend CSS in Organic Groups

**Comment by argiepiano** [comment]
@olafgrabienski there is no css folder in og (only in og_ui, but that is not a good place to add a css class that needs to be accessed even when og_ui is disabled). Would you be willing to add a new og.css file with this class to og/css? 

One small caveat: the field name may be different. OG gives you the option of using a different name for the "Group audience" field (in Configuration > Organic groups > OG field settings). But this should be a rare occurrence.

**Comment by olafgrabienski** [comment]
@argiepiano I've created [pull request](https://github.com/backdrop-contrib/og/pull/134) which adds the CSS folder and file. I'm also going to rename this issue to reflect that in introduces a new CSS file.

**Comment by olafgrabienski** [comment]
The PR adds some top and bottom margin for the common OG fields "Groups audience" and "Group content visibility". Without these margins, in Basis (and possibly other themes), these fields can't be distinguished easily from other fields, e.g. from the "Tags" field in posts.

**Comment by olafgrabienski** [comment]
@argiepiano maybe it's good to wait with merging the PR. At first sight, I think some basic styling is helpful, but I'm not sure about the idea, as it has influence on contrib themes. It would be nice to get some feedback, e.g. from @indigoxela and @stpaultim, about the question.

**Comment by laryn** [comment]
@olafgrabienski Can you add screenshots before and after? Do we need to also pull the CSS in (e.g. in the `.info` file or in some other way)?

**Comment by olafgrabienski** [comment]
Sure, I'll have a look and will provide some screenshots, probably tomorrow.

**Comment by olafgrabienski** [comment]
@laryn Thanks for the hint re pulling in the CSS file – I've updated `og.info` to reference it. See also the screenshot comparison below.

Note: I've made the change directly in the Github interface, as I didn't find a local repo. Due to limited Github experience, there is an unintended commit: https://github.com/backdrop-contrib/og/pull/134/commits/8233a81a9385886b18c68fe3188c7d57bb824185 Can you remove it in case it's disturbing?

Screenshot comparison (Tags vs. Group name)
------------------------

**no CSS**

<img width="400" alt="backdrop-og-no-css" src="https://user-images.githubusercontent.com/14188307/230015946-234c3fea-0c89-433c-a3c9-070d94929f2f.png">

**with CSS**

<img width="400" alt="backdrop-og-with-css" src="https://user-images.githubusercontent.com/14188307/230015955-37336ec9-898e-4f6f-a2eb-64de4b0ffbb8.png">

**Comment by argiepiano** [comment]
I'm looking at the D7 version - for Bartik, the theming for tags makes them look very different from the group (see below). Also the div around the **tags** (not the group) has a `margin-bottom` property that separates them.

That said, given that we will not be able to modify Basis' tag css, I'd say this small change here works for me. With the caveat that if the admin uses a different group audience field name, then this will not apply... (only works for group reference fields named  `og_group_ref` etc.

<img width="867" alt="Screen Shot 2023-04-05 at 1 17 10 PM" src="https://user-images.githubusercontent.com/9938978/230183315-bdaa1b13-dfcf-4afa-878a-49bbcab7b90d.png">
