### ISSUE TITLE
View OG User groups: Title missing

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/og#27]
The view "OG User groups" (`og_user_groups`) is supposed to show groups of a logged in user. However, under **Fields**, the **Title** field is missing, there's only a **Created** field.

Current field:

- OG membership: Created (Member since)

Expected fields
  (reference: http://modulesunraveled.com/organic-groups-7x-2x/organic-groups-views around 2 min 40sec):

- OG membership: Created (Member since)
- (Group node from OG membership) Content: Title (Group)

**Comment by laryn** [comment]
~~Probably related: it seems there's a "Broken/missing handler" under relationships in this view.~~
Scratch. That was a fresh install where I hadn't created a `Group` or `Group Content` content type yet.

**Comment by laryn** [comment]
Thanks @olafgrabienski ! Closed with https://github.com/backdrop-contrib/og/commit/24b4f3e94b9dfa5134b7230cfbb8e63d3f93773c
