### ISSUE TITLE
Error with Field og_user_node block

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/og#29]
When I place the block "Group membership (og_user_node)" in the default layout and visit a page which uses the layout, I get a blank page with the following error:

> Call to undefined method stdClass::bundle()

The whole message in DBlog is:

> Call to undefined method stdClass::bundle() in FieldBlock->getContent() (line 89 of [...]/core/modules/field/field.block.inc).

**Comment by olafgrabienski** [comment]
Actually, I'm not sure what the block "Group membership (og_user_node)" is for. The description says: "Field from the available user account content."

**Comment by indigoxela** [comment]
> ... I'm not sure what the block "Group membership (og_user_node)" is for

That's just a field, which contains a link to the group this content or user is member of. Probably not essential, but shouldn't lead to WSOD, either.

**Comment by argiepiano** [comment]
It seems like this issue has been fixed along the way as we fixed several issues related to the tests. 

Specifically this block shows the groups the logged in user is subscribed to. One thing I did notice is that, when you add a user to a group, that user will not see the group listed in that block until there is a cache clearing. I don't know if this is a bug or how it's supposed to work.

**Comment by laryn** [comment]
Closing based on @argiepiano's summary. @olafgrabienski please reopen if needed.

**Comment by olafgrabienski** [comment]
> It seems like this issue has been fixed along the way ...

Indeed! Using the current code base, the block works on my testsite where it lists all groups the current logged-in person is member of.
