### ISSUE TITLE
Warning: Warning: Invalid argument supplied for foreach() in og_context_determine_context() 

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/og#3]
I'm seeing the following warning message quite a bit in the Watchdog log:

Warning: Invalid argument supplied for foreach() in og_context_determine_context() (line 441 of /app/backdrop/modules/og/og_context/og_context.module).

**Comment by laryn** [comment]
I haven't even enabled `og_context` yet to be honest...

**Comment by laryn** [comment]
It looks like `og_context` should have two default selections that are not being pre-selected by CMI in Backdrop:

![Screen Shot 2020-11-15 at 7 34 36 AM](https://user-images.githubusercontent.com/871421/99186318-1a103b80-2715-11eb-9aff-dc361c5d9fd8.jpg)

![Screen Shot 2020-11-15 at 7 34 28 AM](https://user-images.githubusercontent.com/871421/99186330-31e7bf80-2715-11eb-97b9-d197c15a2c99.jpg)

I'm sure this is a Coder Upgrade cleanup task. e.g.

 - https://github.com/laryn/og/blob/7118f8d916ef9a8735345a2c8447802402c86065/og_context/config/og_context.settings.json

**Comment by argiepiano** [comment]
Now that entityreference_prepopulate has been ported and test-related issues have been fixed, this is no longer an issue. This can probably be closed.

<img width="1223" alt="Screen Shot 2022-04-26 at 8 59 16 PM" src="https://user-images.githubusercontent.com/9938978/165430974-bf66c5f5-96d6-4f2d-b22e-f2108d4db360.png">

**Comment by laryn** [comment]
Just installed and this is looking good. Agreed that this can be closed.
