### ISSUE TITLE
Replace entity_import with entity_plus_import

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/og#33]
OG uses an undefined function - `entity_import()`.  This function has been queued in Entity Plus to be added as `entity_plus_import()`. See  https://github.com/backdrop-contrib/entity_plus/issues/121  . This addition to Entity Plus will be released very soon in version 1.0.15.

There are 3 instances  of `entity_import()`  in OG, all of them in `og.rules_defaults.inc`.  

They produce a fatal PHP error when enabling OG with Entity Plus patched with https://github.com/backdrop-contrib/entity_plus/pull/120

**Comment by argiepiano** [comment]
I need to add that this fatal error only happens if you have Rules enabled.

BTW, it's weird that OG doesn't depend on Rules, given all the default rules provided in og.rules_defaults.inc.

**Comment by laryn** [comment]
Thanks @argiepiano !

I suppose the Rules thing indicates it's possible to use OG without Rules, but that it provides a lot of value-added defaults for Rules if you do install it. I double checked and D7 doesn't have a dependency on Rules, although there is a fair amount of `if (module_exists('rules'))` throughout the code...
