### ISSUE TITLE
Integrate CI

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/og#36]
There are a lot of tests to fix here. I took a start this morning. But would be good to be able to see the whole test suite run.

**Comment by stpaultim** [comment]
What do we need to make this happen (from someone who is clueless in this area)?

I don't think I can do this, but I might be able to help recruit or organize resources if I better understand the problem.

Do we have CI on any other contrib projects?

**Comment by bugfolder** [comment]
> Do we have CI on any other contrib projects?

[Rules](https://github.com/backdrop-contrib/rules) and [Ubercart](https://github.com/backdrop-contrib/ubercart), courtesy of @laryn.

**Comment by olafgrabienski** [comment]
What is `CI`?

**Comment by laryn** [comment]
@olafgrabienski "Continuous Integration" -- in this case using Github Actions to run automated tests on all PRs to the project, for example.

**Comment by laryn** [comment]
@docwilmot See https://github.com/backdrop-contrib/og/actions

![Screen Shot 2022-02-16 at 12 08 47 PM](https://user-images.githubusercontent.com/871421/154328454-d4cb73dd-fd5f-4b08-bf1e-a4f769681609.jpg)


It should trigger tests on all PRs now.
