### ISSUE TITLE
Backdrop LIVE

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/og#37]
I'd like to suggest that someone more familiar than me host a session on Organic Groups at Backdrop LIVE. We just need to identify a host and pick a time slot. 

No one needs to prepare a presentation, but I think it would be helpful is someone were prepared to do a short demonstration of whatever progress has been made by then. OR, a short demonstration of a newly working module (let's be optimistic). 

If the module is working by then, it's a chance to talk about the success and show it off and share lessons learned for our next complicated port. If it's not working, we can discuss blockers and try to recruit the resources we need to get it finished or come up with a strategy.

**Comment by stpaultim** [comment]
This is done. I'll close this issue. https://events.backdropcms.org/schedule

**Comment by olafgrabienski** [comment]
Related / more information:

- https://github.com/backdrop-contrib/og/issues/30#issuecomment-1042802998
- https://events.backdropcms.org/sessions/organic-groups-past-present-future
