### ISSUE TITLE
Unable to create Content Type of type = Group content

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/og#4]
The instructions in the readme suggest that one should first create a content type of type = Group and then create a content type of type Group Content. 

Initially, the option to create a content type of type = Group Content was not available (grayed out), until I created a field bundle here - /admin/config/group/fields.

Once I created a simple field bundle (having no idea what they are), I went back to create a new content type of type = Group Content and the option was no longer greyed out. However, after selecting this option and saving, I went back to my new content type only to find that this setting was NOT saved.

Something is broken here OR I just don't understand what I'm doing. If I figure it out, I will submit a PR to improve the instructions. :-) 

I'll try to experiment some more and figure this out. Maybe I need to try this in Drupal first.

**Comment by stpaultim** [comment]
I installed OG on a Drupal 7 site and noticed right away that upon installation, ~~it already has the following field set up:~~ No, it didn't have this set up. Rather, once I created a content type called Group of OG type Group, it created this. 

![OG_field_settings___Organic-](https://user-images.githubusercontent.com/3144571/99138587-43d34080-25f7-11eb-9b8d-753ebe41b78f.png)

When I did the same thing in Backdrop CMS, this field did not get set up.

**Comment by laryn** [comment]
Thanks @stpaultim -- I do see where this is happening and why. I'll try to submit a PR next week.

**Comment by stpaultim** [comment]
@laryn - Thanks. I'm ready to do more testing, when you are able to submit this fix.

**Comment by stpaultim** [comment]
@laryn - Just a though. On an issue like this where you have some confidence of the problem and where it is happening, if you were to provide a quick summary of that information, I MIGHT be confident enough to try submitting a PR myself (and doing some initial testing).

**Comment by laryn** [comment]
@stpaultim I [pushed my local work into a WIP branch](https://github.com/laryn/og/tree/issue-4) (I don't think it's complete yet) so feel free to take a look and see the direction I'm looking. Basically some Coder Upgrade todo's that were not done. I saw another issue that I'll post separately that you are welcome to look into as well (I'll tag you there).

**Comment by laryn** [comment]
@stpaultim This seemed to work as expected when I was testing this morning and since we have no formal release and are in heavy development yet, I've merged it to the main branch. Care to test in a fresh database on your end to verify? There are a few new issues added and I'd love to review a PR on any of them... :)

**Comment by laryn** [comment]
On further testing with a new database I'm not certain this is solved. Reopening until verified and likely still directly related to https://github.com/laryn/og/issues/10 .

**Comment by laryn** [comment]
@stpaultim Try again?

**Comment by stpaultim** [comment]
@laryn Yes - this just worked for me with a fresh database. I ran into another problem, but will check for existing issue and/or open an new one.

But, I was able to create a content type of group content as expected.
