### ISSUE TITLE
Invalid boolean values in the config files 

### ISSUE THREAD

**Issue by VasasA** [backdrop-contrib/og#40]
Backdrop cannot read boolean values with quotation mark from JSON files. 
For example:
Invalid:
`og_node_access_strict": "TRUE",`

Valid:
`og_node_access_strict": true,`

I created a commit in my PR.

**Comment by oadaeh** [comment]
I put this comment directly on the commit, but I think it got missed:
According to https://docs.backdropcms.org/php-standards they should be `TRUE` and `FALSE`, not `true` and `false`, i.e., in all uppercase.

**Comment by VasasA** [comment]
Using the `TRUE` and `FALSE` generates error: "The configuration file "og.settings" is not properly formatted JSON."
![kép](https://user-images.githubusercontent.com/8567234/155019121-ea51717d-5ba5-4256-a6a8-220e23920b89.png)

**Comment by oadaeh** [comment]
Ah, you are correct. I was not paying attention that they were JSON values. Sorry about the interruption.

**Comment by VasasA** [comment]
No worries 😃

**Comment by VasasA** [comment]
The PR is merged, so this issue can be closed.
