### ISSUE TITLE
Not possible to remove group members (Bug)

### ISSUE THREAD

**Issue by schoenid** [backdrop-contrib/og#43]
While trying to remove a group member, the notification "The membership was removed." occurs, but the member is still there.
It's state can be changed to pending, active or blocked without problems.
On states pending or active the member itself has the option to "Unsubscribe from group". If that link is clicked, the "Unsubscribe" button appears, but after clicking it, the membership is not removed.

Backdrop CMS | 1.21.2
No messages in log reports.

**Comment by olafgrabienski** [comment]
Just confirmed while testing https://github.com/backdrop-contrib/og/issues/45#issuecomment-1058257180.

Not sure if it's related, but in Drupal you can see the system action "Remove from group" (`og_membership`) in the user interface. In Backdrop, Actions have been changed, and I don't know how to check if that action still exists.

**Comment by indigoxela** [comment]
Also confirmed, and it's a one-liner fix actually. It turned out that OgMembership extends (core) Entity, but doesn't override function id().

In includes/og.membership.inc:

```
class OgMembership extends Entity {
  /**
   * Implements EntityInterface::id().
   */
  public function id() {
    return $this->id;
  }
```
A PR has to wait until a regression from my previous PR gets fixed (unrelated issue).

**Comment by indigoxela** [comment]
A PR is now available for testing and review: #53

**Comment by olafgrabienski** [comment]
Great, many thanks for the PR! I can test it probably Monday.

**Comment by olafgrabienski** [comment]
I've tested the PR. I guess it doesn't fix the issue, or only partly. Steps to reproduce:

- As admin, go to the *People* page of a group, e.g. `group/node/5/admin/people`.
  You see a list of group members.
- Click the "remove" link next to a member.
  Note: I'm not sure, but IIRC the "remove" link was missing before the PR. I guess, this is the fixed part.
- On the confirmation page, click the "Remove" button.
  You return to the *People* page, and see the message "The membership was removed."
  However, the 'removed' member is still there (part of the list).

**Comment by indigoxela** [comment]
@olafgrabienski many thanks for testing.

A question: how did you apply the patch? Did you verify the code is there? Important: did you flush caches?

**Comment by olafgrabienski** [comment]
> Did you verify the code is there?

Ha, caught me! Actually, I *missed* to apply the patch (got confused while changing something else on the test site).

And: after applying the patch, I *am* able to remove the group member, so the PR works for me!

(Tested both the "remove" link as admin, and the "Unsubscribe from group" link as member.)

**Comment by schoenid** [comment]
Great !!!
Just works fine on my home installation.

Thanks very much.

**Comment by laryn** [comment]
Thanks for the report (and testing) @schoenid, and the PR @indigoxela! Thanks for testing @olafgrabienski! Merged.
