### ISSUE TITLE
OG Configuration files are "not owned by any module"

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/og#48]
While synchronizing config across environments, I often get errors about the og config files. 

I have the OG module enabled, and yet I get errors when attempting to import this file:
```
The configuration "og.settings" is not owned by any module. Try enabling the module that provides this configuration, then importing again.
```

I have both disabled and uninstalled "Organic groups context" but still get this error when attempting to sync:
```
The configuration "og_context.settings" is not owned by any enabled module, so it cannot be deleted. If you have disabled this module, either enable the module and try the import again, or uninstall the module entirely to clean up left-over configuration.
```

These errors most often occur when a module has not yet implemented `hook_config_info()` but I haven't reviewed he code yet to see if that's the case here.

**Comment by jenlampton** [comment]
For these two cases there was an instance of `hook_config_info()` but the `return` statement was omitted.  I do this myself more often than I'd like to admit. Happy to be able to fix it here :)

**Comment by laryn** [comment]
Thanks @jenlampton -- merged!
