### ISSUE TITLE
Convert role ID query to use CMI

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/og#5]
In various places, queries and references to "role ID" need to be converted to work with Backdrop's CMI. For example:

 - https://github.com/laryn/og/blob/1.x-2.x/og.module#L2687

@stpaultim Does this look like an issue you'd like to take a crack at?

**Comment by stpaultim** [comment]
Yes, I'll take a crack at this now.

**Comment by stpaultim** [comment]
Any additional information would be great. But, I suspect I can figure this out. It looks like for this initial example that what I need to do check config files for permissions instead of the database, right?

I'll have to look for another example of how this is done.

**Comment by laryn** [comment]
Yes, we won't need to convert roles to role ids since they are just stored as roles in Backdrop. And we won't need to query the database but should be able to just use CMI and/or api calls to check permissions.

**Comment by stpaultim** [comment]
OK, I spent some time on this, but I'm very much not sure what I'm doing and running out of time. I think I'm going suggest someone else do this. Sorry.

**Comment by laryn** [comment]
@stpaultim I may have sent you on a goose chase with this one. I'm not super familiar with OG and didn't realize that these roles are specific to OG, not the site-wide roles. I'm not yet sure if it makes sense to convert them (or anything else OG-related) to CMI.

**Comment by argiepiano** [comment]
Yes, OG roles are specific to OG and different from core roles. It's Ok for them to continue to be stored in the database for now.
