### ISSUE TITLE
Find replacement for hook_entity_property_info()

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/og#59]
Seems to play an important role re membership info for group content.

https://github.com/backdrop-contrib/og/blob/1.x-2.x/og.module#L193

No such hook in Backdrop, neither in core nor in entity_plus.

FTR: https://www.drupal.org/docs/7/api/entity-api/entity-property-information

**Comment by argiepiano** [comment]
This hook does exist in Entity Plus. It's invoked [in this line](https://github.com/backdrop-contrib/entity_plus/blob/dbdba44c04a4bb4b5e22a9fa891711a0fc1ef8d5/includes/entity_plus.property.inc#L37) of Entity Plus. 

It'd be helpful to know the nature of the errors related to this hook.

**Comment by indigoxela** [comment]
> This hook does exist in Entity Plus.

Yes it does! How did I miss that? So this should actually work without any changes to code in og.

Lots of things happened recently, so possibly this whole issue is obsolete. To make sure, I'd suggest to wait for the latest PR to get merged and revisit the remaining problems. Just to verify, this issue can get closed with "works as designed".

**Comment by laryn** [comment]
> Just to verify, this issue can get closed with "works as designed".

Okay, done! Reopen if needed...
