### ISSUE TITLE
How to perform EntityFieldQuery for entities with more than one OG audience field

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/og#69]
This is here to document an alternative way to perform EntityFieldQuery for entities with more than one OG audience field.

- Bug description: #67 
- Related D7 issue: [Cannot make an EntityFieldQuery using two OG fields as condition](https://www.drupal.org/project/og/issues/2039903#comment-14492067)
- Solution based on [Comment 12 of the D7 issue](https://www.drupal.org/project/og/issues/2039903#comment-10010179)

Instead of:
```php
    $query = new EntityFieldQuery();
    $result_will_fail = $query
      ->entityCondition('entity_type', 'node')
      ->propertyCondition('type', $node->type)
      ->fieldCondition('og_group1_ref', 'target_id', $group1->nid)
      ->fieldCondition('og_group2_ref', 'target_id', $group2->nid)
      ->execute();
```

Use:
```php
    $query = new EntityFieldQuery();
    $result1 = $query
      ->entityCondition('entity_type', 'node')
      ->propertyCondition('type', $node->type)
      ->fieldCondition('og_group1_ref', 'target_id', $group1->nid)
      ->execute();

    $query = new EntityFieldQuery();
    $result2 = $query
      ->entityCondition('entity_type', 'node')
      ->propertyCondition('type', $node->type)
      ->fieldCondition('og_group2_ref', 'target_id', $group2->nid)
      ->execute();

    $result_ids = array_intersect(array_keys($result1['node']), array_keys($result2['node']));
```
Of course, be sure to check that `$result1['node']` and `$result2['node']` are set before the `array_intersect`.

**Comment by laryn** [comment]
@argiepiano Should this get moved into the Wiki for posterity? (I just opened up the Wiki to public edits)

**Comment by argiepiano** [comment]
Sounds like a good idea!

**Comment by argiepiano** [comment]
I created a page, but please check - it's not appearing correctly in the wiki index

**Comment by argiepiano** [comment]
Closing this - check the Wiki for these directions.
