### ISSUE TITLE
Notice: Undefined index: total_1 in og_ui_handler_area_og_membership_overview->options_form()

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/og#81]
Notice thrown when editing the Header region of View og_members_admin

**Comment by argiepiano** [comment]
PR #82 ready for review and testing.

**Comment by argiepiano** [comment]
Any thoughts or feedback on this PR?

**Comment by olafgrabienski** [comment]
> Undefined index: total_1 in og_ui_handler_area_og_membership_overview->options_form()

Confirmed, with the exception that on my site it's `total_3`, not `total_1`. After applying the patch, I get no new notices, so the PR works for me!

**Comment by argiepiano** [comment]
Thank you for testing, @olafgrabienski!
