### ISSUE TITLE
Clarification regarding JOIN / Subscribe message

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/og#89]
I'm testing the module now and notice that when a user wants to JOIN a group they are asked to complete a "Request Message."

It's not clear to me what is happening with those messages. They don't seem to be stored, but I can't confirm that they are being sent either - since, I'm working locally and I'm not entirely sure if Backdrop is supposed to send emails. 

Opening this ticket to either get clarification on how this is supposed to work AND/OR confirmation that this is working the way it's supposed to (since, I'm not able to confirm it myself at this point).

![image](https://user-images.githubusercontent.com/3144571/169181172-3671b309-82dc-44f4-ad9b-fae58a21b08a.png)

**Comment by stpaultim** [comment]
Quick note: My initial expectation was that as the group manager I would be able to read these messages in the UI before confirming new members to the group.

But, now I suspect that these messages are only sent via email.

**Comment by stpaultim** [comment]
It seems that these messages are sent via rules. But, there is not requirement that the rules module be enabled and that the needed rules be enabled.

Once I enabled these rules, I am getting a watchdog message telling me that an email was sent, but I still have't received the email - probably because I'm working locally in Lando.

**Comment by argiepiano** [comment]
Supposedly this field should appear in the members admin View that you get within the group node, in the group tab when you view the node. But it's not working in Bd - I'll create an issue.

Furthermore Views need to be converted to CMI - all of them are in php code.

**Comment by stpaultim** [comment]
I figured out where this message is in the UI. 

------
This is a user requesting access to a group. 
![image](https://user-images.githubusercontent.com/3144571/169196107-63329939-7dc1-4d4e-9a4b-ffff50c099ce.png)

------

Then the group manager goes here. 
![image](https://user-images.githubusercontent.com/3144571/169196257-a8dd9bad-5b12-4499-b4c5-c88368af3d7f.png)

If you do, you will see the message here:
![image](https://user-images.githubusercontent.com/3144571/169196309-65fd08fd-a19b-45a0-a22f-bd86e66c7531.png)

**Comment by argiepiano** [comment]
I just restored the Request Message field to the view you mentioned in your snapshot. So now, there will be a new column between "Member since" and the operation links column. 
PR #92.

Since you are working with an existing installation, you'll need to manually import the modified view - you can get that from the PR inside og/config

Since this is solved, I'll close this. Feel free to re-open if you run into issues.
