### ISSUE TITLE
Notice: Undefined index: in og_handler_field_group_audience_state->render()

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/og#90]
Still not sure what exactly is triggering this message in the logs, but I'm getting this while doing some general testing.

```
Notice: Undefined index: in og_handler_field_group_audience_state->render() (line 15 of 
/app/modules/og/includes/views/handlers/og_handler_field_group_audience_state.inc).
```

![image](https://user-images.githubusercontent.com/3144571/169181984-53216d9e-3014-4ce6-b698-cc32ece58de1.png)

**Comment by argiepiano** [comment]
It'd be helpful if you provided more details: for example, when this happened, what was your group setup? Did you have a node group and a node group content? This handler is used by Views to show the state of a user, either active, pending or blocked.

**Comment by stpaultim** [comment]
@argiepiano - I understand that I didn't really provide enough info, but it was all I had at the time. Was hoping I might be able to gather more later. 

In fact, I started over and have re-enabled almost everything I did before and this time, no error message. I will try a bit longer, if I can't recreate it, I'll close it.

**Comment by stpaultim** [comment]
I'm going to close this issue, because I can't recreate it. 

I was thrashing around a bit when I started, turning things on and off at random and might have created a VERY unusual situation that is not worth worrying about.
