### ISSUE TITLE
View: OG all user group content - Not showing all the correct content

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/og#93]
As I understand it, this view should be showing all the content that belongs to all the groups that the current user belongs to. 

`admin/structure/views/view/og_all_user_group_content`

In my tests, it's only showing content from one group at a time. 

It is still possible that this is user error, but I'm continuing to test. Opened this issue in case anyone else has additional information that might help me.

STEPS TO RECREATE:

1) Create two groups 
2) Create one piece of content for each group
3) Create a test user and have then join both groups
4) Create a block display of this view `admin/structure/views/view/og_all_user_group_content` and place the block on the default layout.
5) Notice that the block never displays content from more than one group at a time.

**Comment by stpaultim** [comment]
I think I found the problem. I believe that the contextual filters needs this setting:

![image](https://user-images.githubusercontent.com/3144571/169208095-3da60633-1369-4eda-b676-e4c997fab9f7.png)

**Comment by stpaultim** [comment]
This PR does two things:

1) Add the "Allow Multiple Values" setting that is required here.
2) Adds a block display to the view.

Prior to this PR the view did not have any useful displays, only a master display. 

I think it's safe to say that in Backdrop it should come with a block display.

**Comment by argiepiano** [comment]
Great sleuthing! Thanks for the PR. Works as expected.
