### ISSUE TITLE
Improve OG field setting UI

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/og#96]
The OG field settings UI leaves much to be desired. It's extremely confusing, as the "Add field" button appears below the vertical tabs, leading one to believe that the vertical tabs do something to the configuration, while in fact they are only informational.

I propose the following changes. From the current:
<img width="958" alt="Screen Shot 2022-05-19 at 9 35 08 AM" src="https://user-images.githubusercontent.com/9938978/169338242-b36f31eb-5416-4862-929c-5666db208d28.png">
 
To one with better organization and titles:
<img width="969" alt="Screen Shot 2022-05-19 at 9 26 05 AM" src="https://user-images.githubusercontent.com/9938978/169338336-f2a60988-e061-4b3a-b88f-e6af2ad1d57e.png">

I will submit a PR shortly for this. Feedback ppareciated!

**Comment by argiepiano** [comment]
PR #96. Feedback please!

**Comment by stpaultim** [comment]
@argiepiano - I'm working on some suggestions for this page. 

Is it just me, or does this statement not make sense in this location. 
![image](https://user-images.githubusercontent.com/3144571/169447237-5a1d01d0-f087-41e5-acb2-8cde47d6c999.png)

**Comment by argiepiano** [comment]
That little phrase changes depending of the OG field you pick. It's a short explanation of what the field does.  In this case it's telling you that adding a "Groups audience" field to an entity will do two things: it will make this entity a "group content" entity, and (2) it will determine to which group this "group content" is assigned.

Perhaps there is a better way to explain this?

**Comment by stpaultim** [comment]
Here is something I'm working on.

![image](https://user-images.githubusercontent.com/3144571/169448107-1d416d1e-fc05-4cf2-a55d-6b6e3c72cf71.png)

**Comment by stpaultim** [comment]
@argiepiano  I've provided an new PR with some changes. My PR should include the changes in your original PR. 

Feel free to edit my PR or use parts of it.

**Comment by argiepiano** [comment]
@stpaultim I think this looks good and makes the UI easier to understand. I'd like to give @olafgrabienski, @VasasA, @laryn  and @schoenid an opportunity to chime in if they wish, since they've been involved in other OG issues.

**Comment by VasasA** [comment]
OG module is compex. So the more informative pages are very useful. I like @stpaultim solution (PR #99).
Some little things:
- There are two unnecessary space characters in line 1033 in `og_ui.admin.inc`
- In Firefox the position of the help list is too left. (Correct in Chrome.)
![kép](https://user-images.githubusercontent.com/8567234/169599205-b53203ac-444f-4b11-9eea-52ad9db0c4cd.png)

**Comment by olafgrabienski** [comment]
> I'd like to give [...] an opportunity to chime in

I like the overall direction, especially the collapsible help section. I'd love to have a closer look, but I'm not sure if I find time the next days. We'll see!

**Comment by stpaultim** [comment]
@VasasA and @olafgrabienski - Thanks for feedback. Those items should all be fixed.

**Comment by schoenid** [comment]
Looks great!

**Comment by argiepiano** [comment]
Thanks @stpaultim  - I added one small comment. Let's wait until you make that small change and @olafgrabienski can also take a look before merging. Thank you all!

**Comment by olafgrabienski** [comment]
Thanks for your patience, Alexjandro and Tim! @stpaultim I've added some minor comments directly in the PR.

**Comment by stpaultim** [comment]
@argiepiano - I've updated the PR to include the last changes that @olafgrabienski suggested. 

Do we want to discuss the "Select one" label now or hold off?

![image](https://user-images.githubusercontent.com/3144571/169941976-21035ff5-8e93-40d2-ab03-a79d1f6f7143.png)

I'm of the mind, that I would not want to this delay a beta release. I think that the sooner we get a beta release, the sooner we get more testers and more feedback. I would focus on changes right now that are blockers for a beta release.

**Comment by argiepiano** [comment]
Thank you, @VasasA, @olafgrabienski and @stpaultim!
